app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from . import db
from .extension import db

db = SQLAlchemy()

class Item(db.Model):
    __tablename__ = 'items'
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    image_url = db.Column(db.String(200), nullable=True)
    # description = db.Column(db.String(500), nullable=True)
    # images = db.relationship('Image', backref='item', lazy=True)


class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(200), nullable=False)
    item_id = db.Column(db.Integer, db.ForeignKey('items.id'), nullable=False)

    def __repr__(self):
        return f'<Item {self.name}>'
    
class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(150), nullable=False)
    

app/__init__.py
from flask import Flask
from .extension import db
from .models import Item, User
from flask_login import LoginManager
from flask_migrate import Migrate
from .models import db
from flask_restful import Api, Resource, reqparse
import os


def create_app():
    app = Flask(__name__)

    app.secret_key = os.urandom(24)
    
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        from .models import User
        return User.query.get(int(user_id))

    with app.app_context():
        print("creating all tables...")
        db.create_all()
        print("all tables created.")
        print(app.url_map)

    from .routes import main  
    app.register_blueprint(main)  

    api = Api(app)

    #api
    from flask_restful import reqparse
    parser = reqparse.RequestParser()
    parser.add_argument('name', required=True)
    parser.add_argument('description', required=True)

    class ItemResource(Resource):
        def get(self, item_id):
            item = Item.query.get(item_id)
            if item:
                return {'id': item.id, 'name': item.name, 'description': item.description}
            return {'message': 'Item Not Found'}, 404
        
        def post(self, item_id):
            args = parser.parse_args()
            new_item = Item(name=args['name'], description=args['description'])
            db.session.add(new_item)
            db.session.commit
            return {'message': 'Item created', 'id': new_item.id}, 201
        
    api.add_resource(ItemResource, '/api/items', '/api/items/<int:item_id>')

    return app  

app/routes.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, flash
from .models import db, Item, User
from flask_login import login_user, login_required, logout_user, LoginManager
from werkzeug.security import generate_password_hash, check_password_hash
import logging
from werkzeug.utils import secure_filename
import os
from flask import current_app

main = Blueprint('main', __name__)
login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = generate_password_hash(request.form['password'], method='sha256')
        new_user = User(username=username, password=password)
        db.session.add(new_user)
        db.session.commit()
        flash('Successfully Registered!')
        return redirect(url_for('main.login'))
    return render_template('register.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user and check_password_hash(user.password, request.form['password']):
            login_user(user)
            return redirect(url_for('main.item_page'))
        flash('Login failed! Please try again.')
    return render_template('login.html')

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template('login.html')

@main.route('/items', methods=['GET'])
def item_page():
    items = Item.query.all()
    logging.debug(f"Items retrieved: {items}")
    return render_template('items.html', items=items)

@main.route('/items', methods=['POST'])
def create_item():
    item = Item(name=request.json['name']) 
    db.session.add(item)
    db.session.commit()
    return jsonify({'id': item.id, 'name': item.name}), 201

@main.route('/items/<int:item_id>', methods=['PUT'])
def update_item(item_id):
    item = Item.query.get_or_404(item_id)
    item.name = request.json['name']
    db.session.commit()
    return jsonify({'id': item.id, 'name': item.name})

@main.route('/items/<int:item_id>', methods=['POST'])
def delete_item(item_id):
    if request.form.get('_method') == 'DELETE':
        item = Item.query.get_or_404(item_id)
        db.session.delete(item)
        db.session.commit()
        flash('Item deleted !')
        return redirect(url_for('main.item_page'))
    return "method not allowed", 405

@main.route('/update_item/<int:item_id>', methods=['GET', 'POST'])
def update_item_page(item_id):
    item = Item.query.get_or_404(item_id)
    if request.method == 'POST':
        item.name = request.form['name']
        db.session.commit()
        flash('Item updated !')
        return redirect(url_for('main.item_page'))
    return render_template('update_item.html', item=item)

@main.route('/add_item_page', methods=['GET', 'POST'])
def add_item_page():
    if request.method == 'POST':
        item_name = request.form['name']
        image_files = request.files.getlist('images')  
        image_urls = []

        images_dir = os.path.join(current_app.root_path, 'static/images')
        if not os.path.exists(images_dir):
            os.makedirs(images_dir)

        for image_file in image_files:
            if image_file:
                filename = secure_filename(image_file.filename)
                save_path = os.path.join(images_dir, filename)

                if os.path.exists(save_path):
                    base, extension = os.path.splitext(filename)
                    counter = 1
                    while os.path.exists(save_path):
                        filename = f"{base}_{counter}{extension}"
                        save_path = os.path.join(images_dir, filename)
                        counter += 1

                try:
                    image_file.save(save_path)
                    image_urls.append(f'images/{filename}')  
                except Exception:
                    flash('Error saving image, try again.', 'error')

        if image_urls:
            image_url = ', '.join(image_urls)  
        else:
            image_url = None  

        new_item = Item(name=item_name, image_url=image_url)
        db.session.add(new_item)

        try:
            db.session.commit()
            logging.info("Item added to the database.")  
        except Exception as e:
            logging.error("Error committing to database:", e)
            db.session.rollback()  

        flash('Item added!')
        return redirect(url_for('main.item_page'))

    return render_template('add_item.html')

@main.route('/items/<int:item_id>/view', methods=['GET'])
def view_item(item_id):
    item = Item.query.get_or_404(item_id)
    if not item.image_url:
        flash("No images for this Item !")
    return render_template('view_item.html', item=item)

app/templates/add_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Item</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            color: #333;
        }

        header {
            background-color: #4caf50;
            color: white;
            padding: 4%;
            text-align: center;
        }

        h1 {
            margin: 0;
            font-size: 2.5em;
            text-align: center;
            margin-top: 20px;
        }

        .container {
            max-width: 500px;
            margin: 20px auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 15px;
        }

        .button {
            display: inline-block;
            background-color: #008cba;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin-top: 10px;
        }

        button:hover {
            background-color: #005f73;
        }

        .back-link {
            display: inline-block;
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <h1>Add Item</h1>
    </header>
    <div class="container">
        <form action="{{ url_for('main.add_item_page') }}" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">Item Name:</label>
                <input type="text" id="name" name="name" class="form-control" required>
                <label for="images">Upload Images:</label>
                <input type="file" name="images" multiple required>
            </div>
            <button type="submit" class="button">Add Item</button>
        </form>
        <div class="back-link">
            <a href="{{ url_for('main.item_page') }}" class="button">Back to Items</a>
            <a href="{{ url_for('main.home') }}" class="button">Back to Home</a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/header.html
<style>
    .nav-item {
        text-align: center;
    }
</style>

<nav class="navbar navbar-expend-lg navbar-light bg-light">
        <div class="container">
            <a class="nav-brand" href="http://127.0.0.1:5000/">Karibu</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:5000/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:5000/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:5000/register">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>KARIBU</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            color: #333;
        }

        header {
            background-color: #4caf50;
            color: white;
            padding: 4%;
            text-align: center;
        }

        h1{
            margin: 0;
            font-size: 2.5em;
        }

        .welcome-message {
            text-align: center;
            margin: 50px 0;
            font-size: 1.5em;
            padding: 10%;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .button {
            display: inline-block;
            background-color: #008CBA;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin: 5px;
        }

        .button:hover {
            background-color: #005f73;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="http://127.0.0.1:5000/">Kaze</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="http://127.0.0.1:5000/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="http://127.0.0.1:5000/login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="http://127.0.0.1:5000/register">Register</a>
                        </li>
                    </ul>
                    </ul>
                </div>
            </div>
        </nav>

        <header>
            <h1>AMAHORO</h1>
        </header>
        
        <div class="welcome-message">
            <p>This app allows you to manager your items easily , so enjoy !!</p>
            <a href="{{ url_for('main.login') }}" class="button">Login</a>
            <a href="{{ url_for('main.register') }}" class="button">Register</a>
            <a href="{{ url_for('main.item_page') }}" class="button">View Items</a>
            <a href="{{ url_for('main.add_item_page') }}" class="button">Add Item</a>
        </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </div>
</body>
</html>

app/templates/items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Items</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            margin: 5px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        .button:hover {
            background-color: #0056b3;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Items</h1>
    <a class="button" href="{{ url_for('main.add_item_page') }}">Add New Item</a>
    <a class="button" href="http://127.0.0.1:5000/">Back to Home</a>


    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>
                        <form action="{{ url_for('main.delete_item', item_id=item.id) }}" method="POST" style="display: inline;">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="button" style="background-color: red; color: white; border: none;">Delete</button>
                        </form>
                        <a class="button" href="{{ url_for('main.update_item_page', item_id=item.id) }}">Update</a>
                        <a class="button" href="{{ url_for('main.view_item', item_id=item.id) }}">View</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Login</title>
</head>
<body>
    <div class="container mt-5">

        <div>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:5000/">INJIZA</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:5000/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:5000/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:5000/register">Register</a>
                    </li>
                </ul>
                </div>
            </div>
        </nav>
    </div>

    <h2 class="text-center">Login</h2>
    <form action="/login" method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>    
        </div>  
        <button type="submit" class="btn btn-primary btn-block">Login</button>
    </form>
   
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Register</title>
</head>
<body>
    <div class="container mt-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="http://127.0.0.1:5000/">Iyandikwa</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="http://127.0.0.1:5000/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="http://127.0.0.1:5000/login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="http://127.0.0.1:5000/register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <h2 class="text-center">Register</h2>
        <form action="/register" method="POST">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Register</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/update_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Item</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            color: #333;
        }

        header {
            background-color: #4caf50;
            color: white;
            padding: 4%;
            text-align: center;
        }

        h1 {
            margin: 0;
            font-size: 2.5em;
            text-align: center;
            margin-top: 20px;
        }

        .container {
            max-width: 500px;
            margin: 20px auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 15px;
        }

        .button {
            display: inline-block;
            background-color: #008cba;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin-top: 10px;
        }

        button:hover {
            background-color: #005f73;
        }

        .back-link {
            display: inline-block;
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <h1>Update Item</h1>
    </header>
    <div class="container">
        <form method="POST">
            <div class="form-group">
                <label for="name">Item Name:</label>
                <input type="text" id="name" name="name" class="form-control" required>
            </div>
            <button type="submit" class="button">Update Item</button>
        </form>
        <div class="back-link">
            <a href="{{ url_for('main.item_page') }}" class="button">Back to Items</a>
            <a href="{{ url_for('main.home') }}" class="button">Back to Home</a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/view_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Item</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1{
            color: #333;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            margin: 5px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .button:hover {
            background-color: #0056b3;
        }

        img {
            max-width: 100%;
            height: auto;
            margin-top: 20px;
        }

    </style>
<body>
    <h1>{{ item.name }}</h1>

    {% if item.image_url %}
        {% for img in item.image_url.split(', ') %}
            <img src="{{ url_for('static', filename=img) }}" alt="{{ item.name }}">
        {% endfor %}
    {% else %}
        <p>Sorry, No Images for this Item!</p>
    {% endif %}

    <a class="button" href="{{ url_for('main.item_page') }}">Back to Items</a>
    <a class="button" href="">Command</a>
</body>
</head> 
</html>